repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.9

- repo: local
  hooks:
    - id: unittest
      name: unittest
      entry: python -m unittest src/test/test_atm.py
      language: python
      pass_filenames: false
      additional_dependencies: [pydantic, python-dotenv]
